### ISSUE TITLE
BOM disregards Parts in Groups

### ISSUE THREAD

**Issue by Buckelpiste** [APEbbers/BillOfMaterials-WB#117]
Hi, I have an assembly which I structured in groups, i.e. I organized the parts in groups just to keep an overview (function: Asm4_newGroup, between new body and part info). The BOM function works (almost, but that's another bug, a horizontal bug), but lists only the ungrouped parts. For clarification: I took the Tür_re_K4 out of group K4 just to test the behaviour.  

Workaround is simple: just temporarily ungroup everything.

![image](https://github.com/user-attachments/assets/a5b6d297-1ce4-41ce-9dd3-3be485774e97)

![image](https://github.com/user-attachments/assets/8330d752-f741-457e-a40b-241350970149)

**Comment by Buckelpiste** [comment]
Just to calm you down, I found out how to add columns and get the shape. Horizontal "bug" fixed. Newbie here. 
Is there a help text? I can write one quickly.

**Comment by APEbbers** [comment]
I have not written a wiki page yet. I'll will do that in the coming weeks. 
As asked in your other issue: can you provide me your model? I'll have a look in what is going on.

btw which version of FreeCAD are you working with?

kind regards.

**Comment by APEbbers** [comment]
Hi,

The issue with items in groups within an assembly should now be fixed as well. Can you check if this is the case?
I've updated the Add-on to version 0.1.5.0

**Comment by Buckelpiste** [comment]
Cool, it works. Thanks! So for now, everything works (except for my inaptitude in handling Freecad properly).
