### ISSUE TITLE
What's Shape doing? Shape values too big when LCS outside body.

### ISSUE THREAD

**Issue by Buckelpiste** [APEbbers/BillOfMaterials-WB#118]
This is maybe rather me not being able to use Freecad and BOM and no issue. Anyway, I managed to get a BOM of my assembly, yet the measurements of the shape are insane, like a cubic meter for a plank (see pics of Blende_oben_K1). 
How is the shape calculated? How do I get the dimensions of a part properly?
I suspect it has to with way I inserted them into the assembly. I set up local coordinate systems for each body with negative coordinates, such that I could attach them to another LCS of an already inserted part (I haven't figured out a better way yet). 

Another issue is that parts with equal measurements show up several times under different names of course (maybe because I insert the parts separatly? Again don't know how to do it better.). I can live with that for now.

![image](https://github.com/user-attachments/assets/9ef30ab7-9dec-4997-bf4f-aaf2531b66ec)

![image](https://github.com/user-attachments/assets/909b06e9-77db-4544-a0ea-23e844ef5a90)

![image](https://github.com/user-attachments/assets/1674e6aa-86c5-4f4f-88ae-afee15076d17)

![image](https://github.com/user-attachments/assets/69123268-7143-4752-aa11-499d08c0b12b)

**Comment by Buckelpiste** [comment]
Thanks for looking into it. 

Meanwhile I played around and the problem seems to be a LCS with offset **outside** the body. So, first you create a body, create an LCS for that body, place that LCS somewhere outside the body (offset). Second you insert that body/part in Assembly4 (doesn't matter if you attach it to another LCS, which is why I started that offsetting). Third you create your BOM and there you will find the shape including the offset from the body-LCS. 

I'll send you the model via mail, Github wouldn't let me upload a .fcstd file (or am I dumb?).
How can I see the version of an addon? Freecad is 0.21.2 on Manjaro.

Sorry, the example isn't very clean. 
![image](https://github.com/user-attachments/assets/8c7f531f-5a9c-473d-93ce-59cdb3a368b2)
![image](https://github.com/user-attachments/assets/f630ebc0-b08c-4d04-85ca-cf4c254a81a5)

**Comment by APEbbers** [comment]
Hi,

I noticed that when the LCS was not visible, the values where correct. You can get to the bounding box on to ways. I changed the code and it seems solved.

Can you check if it is solved. And if it seems solved, can you check if it still is correct when you change some angles so it is rotated in 3D about x,y,z? In the past there where some issues with that.

You can get the update via the addon manager or via git hub.  the new version is version 0.1.4.3.

Thanks in advance

**Comment by APEbbers** [comment]
I've found the cause of the issue. It is when the LCS is visible, the boundingbox get's bigger because it includes the visible LCS.
I'm using the boundingbox to get the X,YZ measurements.
a workaround for the time being is to hide the LCS first and than create the BOM.

I'm continue working on this, this evening.

**Comment by APEbbers** [comment]
I've updated the code. Can you see if the issue is solved?
You can update via the Addon manager or via Git

**Comment by Buckelpiste** [comment]
Yes, solved. I replicated the workaround with the old code (invisible LCS). The new code works fine with visible LCS. Thanks a ton!
