### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Zolko-123** [APEbbers/BillOfMaterials-WB#12]
The WB starts fine with the 0.22 development of FreeCAD (0.22.0dev.35594) but not with earlier versions (<0.21). It gives the following error:

```
During initialization the error "UI file does not exist" occurred in /home/hubertz/.local/share/FreeCAD/Mod/BillOfMaterials/./InitGui.py
Please look into the log file for further information
```

I think it's not finding `PATH_TB = os.path.dirname(getsourcefile(lambda:0))` . In Assembly4 I use the following code which works with all versions of FreeCAD:

```
import Asm4_locator
Asm4_path = os.path.dirname( Asm4_locator.__file__ )
```

The file _Asm4_locator.py_ is an empty file

**Comment by APEbbers** [comment]
Thanks. I've changed the line as yo suggested.
