### ISSUE TITLE
Can't find icon for Preferences–page in 0.22.dev

### ISSUE THREAD

**Issue by Be-Cool-Man** [APEbbers/BillOfMaterials-WB#35]
When opening the preferences from FreeCAD (Edit ⇒ Preferences…) I get the warning `Cannot find icon: preferences-bill_of_materials`, and instead of your icon, there is a white square with a black X inside of it.

![grafik](https://github.com/APEbbers/BillOfMaterials-WB/assets/7967418/809975b0-2d5d-4b16-9d10-03a0ec5d64d2)

```
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36166 (Git) AppImage
Build type: Release
Branch: main
Hash: a5ea8023a29b6d7bbf1ebd57b5ed31dd27c5947b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Installed mods: 
  * BillOfMaterials 0.0.5.6
  * Assembly4 0.50.7
  * A2plus 0.4.63
  * BOLTSFC
  * ExplodedAssembly
  * Assembly3 0.12.2
  * sheetmetal 0.4.2
  * fcgear 1.0.0
  * OpenDark 2023.12.17
  * fasteners
  * Help 1.0.3
```

**Comment by APEbbers** [comment]
Thanks for noticing that! There was a naming issue. It should be fixed now.
