### ISSUE TITLE
Assembly type mis detection

### ISSUE THREAD

**Issue by didiergm** [APEbbers/BillOfMaterials-WB#37]
I installed this workbench this morning and using Create Overall BOM (the other two do nothing) BOM Workbench insists that my assembly was not made with A2Plus but MultiBody Not sure if this has consequences on the BOM generated

**Comment by APEbbers** [comment]
Can you see which version is installed from the Add-On manager? Your issue might be related to the other issue that you raised.
I tested from my side and its works. both with FreeCAD 0.21.2 and FreeCAD 0.22dev. 

An option can be to update the workbench with a GitManager like TortuireGit directly in explorer, in the folder of the workbench.

**Comment by didiergm** [comment]
Version 0.0.5 .7 installed 3/3/2024

Also where are good places to ask questions ?

**Comment by APEbbers** [comment]
Hi,

If you can send me your files that would help a lot!

For questions about issues with this WB, here is fine. For more general questions, there is a forum for this WB:  [https://forum.freecad.org/viewtopic.php?t=84982](url)

**Comment by didiergm** [comment]
No problem how do I send them. Should I use the email address I got with the notification of your answer?

**Comment by APEbbers** [comment]
You can use that e-mail indeed or you can also add an attachement to a message here.

**Comment by didiergm** [comment]
[envoi.zip](https://github.com/APEbbers/BillOfMaterials-WB/files/14541106/envoi.zip)

Here are the files, start with "meuble_vide.FCStd" 
It is the first Freecad project I am making, so it may not be either optimum or even the right way to do things, feel free to comment on that, no offence will be taken as I am learning.

**Comment by APEbbers** [comment]
Hi,

I've released a new version 0.05.8. I've fixed two issues:
1. The issue that the wrong assembly is detected
2. The issue that you couldn't select another assembly type.

Can you test it if it works on your side?

Your files look good as far as I can see.

**Comment by didiergm** [comment]
Remove BOM workbench and reinstalled it, got version .8 all right, but
there is a small issue, for some reason the window showing when clicking on
"Create overall BOM" is too small and I cannot see or access the button to
launch the BOM creation : So I could not test

[image: image.png]

**Comment by APEbbers** [comment]
I did the same, and I have no problems. However I'm on windows.

Unfortunately, the picture wasn't uploaded. but maybe you can try to stretch the panel to the left, It might trigger something to snap in the correct position?

**Comment by didiergm** [comment]
In fact, the visible content of the window depends on the size of the
report view at the bottom of the screen (ie mine was fairly large, and it
did not allow to see the last 3 fields (detect assembly typeand button
generate) I suspect this would be the same on Windows

I can now confirm that the auto detection works

Thanks you for your time

Didier

**Comment by APEbbers** [comment]
No problem! Thank you for bringing this up and helping me to improve the WB. I'm closing this issue.
