### ISSUE TITLE
Add width length and pad to BOM list

### ISSUE THREAD

**Issue by didiergm** [APEbbers/BillOfMaterials-WB#38]
Is there a way to have the width length and pad length for each item in the BOM list

**Comment by APEbbers** [comment]
I've not yet implemented it, but it is on the list of features that I want to add.

**Comment by didiergm** [comment]
No pressure (honest!) is there a rough ETA?

**Comment by APEbbers** [comment]
i cannot give you an exact estimate, but currently I'm working on the functionality for the Arch WB. After that I will focus on the shape object from which i hope to calculate mass and dimensions. roughy i would say, 4 to 6 weeks, but don't hold me on that.

**Comment by didiergm** [comment]
I won't promise, I was after something like "Next monday evening" or "Much
later" :)

**Comment by APEbbers** [comment]
I was stuck on the Arch WB, so I decided to look into this request.
I've released version 0.0.6.0. You can now add a few properties from the shape object. These are:
- Bounding box dimensions
- Volume
- Area
- Center of gravity
- mass (System version for now)

The Bounding box dimensions can be a little bit inaccurate. This is caused by FreeCAD itself, not by this WB.

To add the properties: 
1. Select and item in the tree
2. Click "Add or remove columns".
3. Scroll down to select the properties you want.

**Comment by didiergm** [comment]
Sorry to reopen this
Version 0.7
Height, width and Length all mixed up : the 19 is 19mm, from the pad lenght, as you can see it is displayed on every line, but not always in the same column, not sure if this something you can fix, though

'Number	'Qty	'Label	'Description		'Shape - Height	'Shape - Width	'Shape - Length
'1	2	'cote			2300.00003051758	350	19
'3	2	'sol-toit			19	348	740
'4	2	'tiroir_assembly			89	350	740
'4.1	1	'plancher_tiroir			19	348	714
'4.2	1	'cote_tiroir_gauche			70.0000000000002	331	19.0000000000001
'4.3	1	'cote_tiroir			70.0000000000002	331	19.0000000000001
'4.4	1	'fond_tiroir			70	19	714
'4.5	2	'mecanisme			45	250	13
'5	2	'porte_basse			900.000061035156	18.9999999999999	388
'6	2	'facade_tiroir			100	18.9999999999998	780
'6.1	1	'plancher_tiroir			19	348	714
'6.2	1	'cote_tiroir_gauche			70.0000000000002	331	19.0000000000001
'6.3	1	'cote_tiroir			70.0000000000002	331	19.0000000000001
'6.4	1	'fond_tiroir			70	19	714
'6.5	2	'mecanisme			45	250	13
'7	2	'porte_haute			1200	19	388
'8	2	'etagere_fixe			19	348	740
'9	7	'etagere_mobile			19	348	736

**Comment by didiergm** [comment]
Just had an epiphany, it must be related to the plane X,Y,Z on which the part has been drawn

**Comment by APEbbers** [comment]
That makes indeed sense. I'm getting the values from the boundingbox. This is a feature in freecad. At the moment this means that the length is in X direction, the width in Y direction and thickness in Z direction. 

In the future all add an option to change this in the settings menu.
