### ISSUE TITLE
Extra columns, shape length, width and height : do not respect system decimal settings

### ISSUE THREAD

**Issue by didiergm** [APEbbers/BillOfMaterials-WB#61]
Numbers are always exported with a decimal point. In France we use the comma as a decimal separator, so when copy/pasting to a spreadsheet  (libreoffice) number are treated as text, not numbers

As an aside - not sure if it should be changed, if the result comes from a calculation (I guess), there are plenty of digits after the decimal point, otherwise they are integers.

I am sure you'll start to hate me at some point ^^

**Comment by APEbbers** [comment]
Well this is an easy fix! it is actually not related to this WB, but to FreeCAD itself.
When you go to settings you can change the decimal seperator:
The same goes for the digits after the decimal point. You can change it under settings as well.

![image](https://github.com/APEbbers/BillOfMaterials-WB/assets/10145631/f9881af7-7bd0-4d5e-b68e-0d8a08afb61f)
