### ISSUE TITLE
Task dialog not displaying properly.

### ISSUE THREAD

**Issue by PaddleStroke** [APEbbers/BillOfMaterials-WB#62]
![image](https://github.com/APEbbers/BillOfMaterials-WB/assets/19984177/354bdb25-36cd-4350-ac55-1762451f50b3)
Open dark, overlay on. The task panel is weirdly cropped. I would guess it's a problem in the .ui layout.

**Comment by PaddleStroke** [comment]
Hi,
Thanks it does looik much better now. However it is still not perfect both in overlay or without overlay : 
![image](https://github.com/APEbbers/BillOfMaterials-WB/assets/19984177/9b3f8832-dc7b-47c8-9f7c-8621d496a898)
- The taskbox does not expand on width as they usually do.
- The label text of second checkbox is cropped.

**Comment by APEbbers** [comment]
I've redesigned the layout. I'm closing this issue. If with the new layout are issues related to the extra themes. Please open a new issue
