### ISSUE TITLE
Assembly 4 arrays not working properly

### ISSUE THREAD

**Issue by nicklars3n** [APEbbers/BillOfMaterials-WB#80]
Handling of Assembly 4 arrays doesn't seem to work properly. 

For example with a circular array:
- When referencing a part internal to the assembly, the array object is counted as quantity 1
- When referencing a part in an external file, nothing comes up in the BOM

A simple example is attached:
[BillOfMaterials-WB Asm4 Array.zip](https://github.com/APEbbers/BillOfMaterials-WB/files/15293889/BillOfMaterials-WB.Asm4.Array.zip)

FreeCAD version 0.21.2 
Assembly 4 version 0.50.12
BillOfMaterials-WB version 0.0.8.2 from Addon manager

**Comment by APEbbers** [comment]
Hi, 

I was on holiday, but I'm back and have picked this up. I've got it working for patterns with parts. 
I'm still working on patterns with subassemblies. I hope to fix that soon as well

kind regards

Paul

**Comment by APEbbers** [comment]
Hi,

It took me a while to figure out, but the issue should be solved.
Sorry for the delay.

Kind regards,

Paul

**Comment by APEbbers** [comment]
There was as issue where the fix was partly reversed back when working on the UI update
